# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

labels:
  app: ska-tango-charts

subsystem: sys-test

global:
  minikube: false
  tango_host: tango-databaseds:10000
  operator: true

dsconfig:
  configuration_file: data/configuration.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.13
    pullPolicy: IfNotPresent

ska-tango-base:
  itango:
    enabled: true
  vnc:
    enabled: false
  ingress:
    enabled: true
    hostname: tango-base.minikube.local
  tangodb:
    use_pv: true
  deviceServers:
    tangotest:
      command: "/usr/local/bin/TangoTest"
      instances: ["test"]
      postStart: "echo $TEST | grep secret; echo $TEST_TRANSFORM | grep transform"
      secrets:
      - secretPath: skao-team-system/ska-tango-charts
        secretMount: dev
        env:
        - secretKey: test-injection
          envName: TEST
          default: "secret"
        - secretKey: test-transform
          envName: TEST_TRANSFORM
          default: "transform"
          transform: >-
            {{- printf "%s%s" (get .Secrets "test_transform_1") (get .Secrets "test-transform-2") -}}

deviceServersOldVersion:
  tangotestoldversion:
    name: tangotest2
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-java
      tag: 9.5.0
      pullPolicy: IfNotPresent
    command: "/usr/local/bin/TangoTest"
    instances: ["test2"]
    secrets:
    - secretPath: kv/data/groups/ska-dev/system
      env:
      - secretKey: test-injection
        envName: TEST
        default: "minikube-case"
    resources:
      requests:
        cpu: 200m     # 200m = 0.2 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 1Gi
      limits:
        cpu: 500m     # 500m = 0.5 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
        ephemeral-storage: 1Gi
    livenessProbe:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
