image: $SKA_K8S_TOOLS_BUILD_DEPLOY

stages:
  - lint
  - build
  - test
  - deploy
  - integration
  - staging
  - pages
  - publish
  - scan

# Standardised included jobs
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
  CI_POETRY_VERSION: 1.8.2
  # TODO: Add these to the runner environment variables
  CLUSTER_DATACENTRE: stfc-techops
  CLUSTER_ENVIRONMENT: production

# Include CI templates
include:
# Helm Charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

# Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

# k8s steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

# changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

test-chart-templates:
  stage: test
  variables:
    MINIKUBE: "false"
  tags:
  - k8srunner
  image: $SKA_K8S_TOOLS_DEPLOY_IMAGE
  script:
    - helm plugin install https://github.com/quintush/helm-unittest && helm plugin update unittest
    - make k8s-chart-test
    - mkdir -p ./build/reports
    - mv charts/build/chart_template_tests.xml ./build/reports/chart_template_tests.xml
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/reports/chart_template_tests.xml

k8s-test:
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA'
    K8S_VALUES_FILES: "${ENVIRONMENT_VALUES} ${DEP_STRATEGY_VALUES} ${APP_VALUES}"
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://gitlab.com
  secrets:
    ENVIRONMENT_VALUES:
      vault: ${CLUSTER_DATACENTRE}/${CLUSTER_ENVIRONMENT}/default/values.yml@dev
      file: true
    DEP_STRATEGY_VALUES:
      vault: shared/default/operator/values.yml@dev
      file: true
    APP_VALUES:
      vault: skao-team-system/ska-tango-charts/values.yml@dev
      file: true

k8s-test-no-operator:
  extends: k8s-test
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-no-op'
    K8S_VALUES_FILES: "${ENVIRONMENT_VALUES} ${DEP_STRATEGY_VALUES} ${APP_VALUES}"
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://gitlab.com
  secrets:
    ENVIRONMENT_VALUES:
      vault: ${CLUSTER_DATACENTRE}/${CLUSTER_ENVIRONMENT}/default/values.yml@dev
      file: true
    DEP_STRATEGY_VALUES:
      vault: shared/default/no-operator/values.yml@dev
      file: true
    APP_VALUES:
      vault: skao-team-system/ska-tango-charts/values.yml@dev
      file: true
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always
  environment:
    name: test/$CI_COMMIT_REF_SLUG-no-op
    on_stop: stop-k8s-test-no-operator
    auto_stop_in: 1 minute
  rules:
    - exists:
        - tests/**/*

stop-k8s-test-no-operator:
  extends: stop-k8s-test
  when: manual
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-no-op'
  environment:
    name: test/$CI_COMMIT_REF_SLUG-no-op
    action: stop
