{{ define "ska-tango-util.multidevice-config.tpl" }}
{{- $labels := coalesce .local.Values.global.labels .local.Values.labels "label: none" }}
{{- $annotations := coalesce .local.Values.global.annotations .local.Values.annotations }}
{{- $deviceserver := .deviceserver }}
{{- $deviceserver_name := tpl (coalesce .name .deviceserver.name | toString) .local }}
{{- $chart := .local }}
{{- if not .local.Values.global.operator }}

---
# Device Server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $deviceserver_name | toString }}-{{ .local.Release.Name }}-dsconfig-json
  namespace: {{ .local.Release.Namespace }}
  labels:
{{ toYaml $labels | indent 4 }}
    component: configurator
    function: deployment
    intent: enabling
    domain: self-configuration
{{- if $annotations}}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
data:
  configuration.json: |
    {
      "servers": {
        "{{ $deviceserver.server.name }}" : {
          {{- range $index_instance,$instance := $deviceserver.server.instances }}
          {{- if has $instance.name $deviceserver.instances }}
          {{- if hasKey $deviceserver "tmp_start_instance" }},{{end}}
          {{- $_ := set $deviceserver "tmp_start_instance" "1" }}
          "{{ $instance.name }}": {
            {{- range $index_class, $class := $instance.classes }}
            {{- if $index_class}},{{end}}
            "{{ $class.name }}": {
              {{- range $index_device, $device := $class.devices }}
              {{- if $index_device}},{{end}}
              {{- $ctx := (dict "chart" $chart "props_obj" $device) }}
              "{{ $device.name }}": {{ include "ska-tango-util.dsconfig-properties.tpl" $ctx | indent 14 | trim }}
              {{- end }}
            }
            {{- end }}
          }
          {{- end }}
          {{- end }}
        }
      }{{ if $deviceserver.class_properties }},
      "classes": {
        {{- range $index_class_prop_group, $class_prop_group := $deviceserver.class_properties }}
        {{- if $index_class_prop_group}},{{end}}
        {{- $ctx := (dict "chart" $chart "props_obj" $class_prop_group) }}
        "{{ $class_prop_group.name }}": {{ include "ska-tango-util.dsconfig-properties.tpl" $ctx | indent 8 | trim }}
        {{- end }}
      }
      {{- end }}
    }
    {{- $_ := unset $deviceserver "tmp_start_instance" }}
  bootstrap.sh: |
    #/bin/sh
    json2tango -w -a -u data/configuration.json
    rc=$?
    if [ $rc -eq 0 ]; then
      echo "finished normally."
      exit 0
    else
      if [ $rc -eq 2 ]; then
        echo "finished with an update."
        exit 0
      else
        echo "finished with an ERROR."
        exit $rc
      fi
    fi
  {{ $deviceserver.server.name }}.py: |
{{- $context := dict "deviceserver" $deviceserver "DEBUG" $chart.Values.global.DEBUG }}
{{- include "ska-tango-util.entrypoints-script.tpl" $context | nindent 4}}
{{- end }}
{{- end }} # multidevice-config.tpl